/*
 * AboutBoxDialog.java
 *
 * Created on December 12, 2003, 2:20 PM
 */
// Originally came from Trinity Software, LLC copyright 2003 to 2005.
package org.happy.artist.rmdmia.gui;
import java.awt.*;

/**
 * org.happy.artist.rmdmia.gui.AboutBoxDialog class is the Help About Dialog
 * for the ROCI ROS Configuration Manager UI for Java. 
 *
 * @author Happy Artist
 * 
 * @copyright Copyright ©2003-2014 Happy Artist. All rights reserved.
 * 
 */
public class AboutBoxDialog extends javax.swing.JDialog {
    
    /** Creates new form AboutBoxDialog
     * @param parent
     * @param modal
     */
    public AboutBoxDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setSize(389,300);
        setResizable(false);
         // Get the size of the screen
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();

        // Determine the new location of the window
        int w = getSize().width;
        int h = getSize().height;
        int x = (dim.width-w)/2;
        int y = (dim.height-h)/2;
        // Move the window
        setLocation(x, y);               
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        AboutBoxContentPanel = new javax.swing.JPanel();
        lSplashImage = new javax.swing.JLabel();
        AboutBoxButtonPanel = new javax.swing.JPanel();
        AboutBoxOKButton = new javax.swing.JButton();
        CenterPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        copyrightText = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("About RMDMIA - ROS Configuration Manager");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        AboutBoxContentPanel.setLayout(new java.awt.BorderLayout());

        AboutBoxContentPanel.setBackground(new java.awt.Color(240, 240, 240));
        lSplashImage.setBackground(new java.awt.Color(240, 240, 240));
        lSplashImage.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lSplashImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/trinaboutbanner.png")));
        lSplashImage.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        AboutBoxContentPanel.add(lSplashImage, java.awt.BorderLayout.NORTH);

        AboutBoxButtonPanel.setBackground(new java.awt.Color(240, 240, 240));
        AboutBoxButtonPanel.setFont(new java.awt.Font("Arial", 0, 12));
        AboutBoxOKButton.setFont(new java.awt.Font("Arial", 0, 12));
        AboutBoxOKButton.setText("OK");
        AboutBoxOKButton.setMnemonic('O');
	  AboutBoxOKButton.grabFocus();
        AboutBoxOKButton.setFont(new java.awt.Font("Dialog", 0, 12));
        AboutBoxOKButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutBoxOKButtonActionPerformed(evt);
            }
        });

        AboutBoxButtonPanel.add(AboutBoxOKButton);

        AboutBoxContentPanel.add(AboutBoxButtonPanel, java.awt.BorderLayout.SOUTH);

        CenterPanel.setLayout(new javax.swing.BoxLayout(CenterPanel, javax.swing.BoxLayout.X_AXIS));

        CenterPanel.setBackground(new java.awt.Color(240, 240, 240));
        CenterPanel.setFont(new java.awt.Font("Arial", 0, 12));
        jLabel2.setMaximumSize(new java.awt.Dimension(10, 10));
        jLabel2.setMinimumSize(new java.awt.Dimension(10, 10));
        jLabel2.setPreferredSize(new java.awt.Dimension(10, 10));
        CenterPanel.add(jLabel2);

        copyrightText.setBackground(new java.awt.Color(240, 240, 240));
        copyrightText.setFont(new java.awt.Font("Arial", 0, 12));
        copyrightText.setForeground(new java.awt.Color(92, 104, 115));
        copyrightText.setCaretColor(new java.awt.Color(240, 240, 240));
        copyrightText.setLineWrap(true);
        copyrightText.setText("\n\u00a9 2012-2014, Happy Artist. All rights reserved.\n\nWarning: This computer program is protected by copyright law and international treaties. Unauthorized reproduction or distribution of this program, or any portion of it, may result in severe civil, and criminal penalties, and will be prosecuted to the maximum extent possible under law.");
        copyrightText.setWrapStyleWord(true);
        CenterPanel.add(copyrightText);

        jLabel1.setMaximumSize(new java.awt.Dimension(10, 10));
        jLabel1.setMinimumSize(new java.awt.Dimension(10, 10));
        jLabel1.setPreferredSize(new java.awt.Dimension(10, 10));
        CenterPanel.add(jLabel1);

        AboutBoxContentPanel.add(CenterPanel, java.awt.BorderLayout.CENTER);

        getContentPane().add(AboutBoxContentPanel, java.awt.BorderLayout.CENTER);

        pack();
    }//GEN-END:initComponents

    private void AboutBoxOKButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutBoxOKButtonActionPerformed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_AboutBoxOKButtonActionPerformed
    
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AboutBoxButtonPanel;
    private javax.swing.JPanel AboutBoxContentPanel;
    private javax.swing.JButton AboutBoxOKButton;
    private javax.swing.JPanel CenterPanel;
    private javax.swing.JTextArea copyrightText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lSplashImage;
    // End of variables declaration//GEN-END:variables
    
}
