/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.happy.artist.rmdmia.gui;

/**
 *
 * @author aaron
 */
public class TunerPanel extends javax.swing.JPanel {

    /**
     * Creates new form TunerPanel
     */
    public TunerPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelHeader = new javax.swing.JPanel();
        taOverview = new javax.swing.JTextArea();
        splitPaneTuner = new javax.swing.JSplitPane();
        scrollPaneTuner = new javax.swing.JScrollPane();
        tblTuner = new javax.swing.JTable();
        panelTunerControl = new javax.swing.JPanel();
        btnStartTuner = new javax.swing.JButton();
        btnStopTuner = new javax.swing.JButton();
        btnSaveTuner = new javax.swing.JButton();
        btnUpdateConfiguration = new javax.swing.JButton();
        btnHideTuner = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        setEnabled(false);
        setLayout(new java.awt.BorderLayout());

        panelHeader.setLayout(new java.awt.BorderLayout());

        taOverview.setEditable(false);
        taOverview.setColumns(20);
        taOverview.setLineWrap(true);
        taOverview.setRows(5);
        taOverview.setText("Instructions:");
        panelHeader.add(taOverview, java.awt.BorderLayout.PAGE_START);

        add(panelHeader, java.awt.BorderLayout.NORTH);

        tblTuner.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollPaneTuner.setViewportView(tblTuner);

        splitPaneTuner.setRightComponent(scrollPaneTuner);

        panelTunerControl.setLayout(new javax.swing.BoxLayout(panelTunerControl, javax.swing.BoxLayout.Y_AXIS));

        btnStartTuner.setMnemonic('S');
        btnStartTuner.setText("Start");
        btnStartTuner.setToolTipText("Start sampling message data lengths with performance tuner message handlers for the selected topics/services.");
        btnStartTuner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartTunerActionPerformed(evt);
            }
        });
        panelTunerControl.add(btnStartTuner);

        btnStopTuner.setMnemonic('t');
        btnStopTuner.setText("Stop");
        btnStopTuner.setToolTipText("Stop sampling data length, and return to normal message handlers.");
        btnStopTuner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopTunerActionPerformed(evt);
            }
        });
        panelTunerControl.add(btnStopTuner);

        btnSaveTuner.setMnemonic('a');
        btnSaveTuner.setText("Save Data To File");
        btnSaveTuner.setToolTipText("Save sampled data to file.");
        btnSaveTuner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveTunerActionPerformed(evt);
            }
        });
        panelTunerControl.add(btnSaveTuner);

        btnUpdateConfiguration.setMnemonic('p');
        btnUpdateConfiguration.setText("Update Configuration");
        btnUpdateConfiguration.setToolTipText("Update the ROS Configuration Tuned Data Lengths");
        btnUpdateConfiguration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateConfigurationActionPerformed(evt);
            }
        });
        panelTunerControl.add(btnUpdateConfiguration);

        btnHideTuner.setMnemonic('d');
        btnHideTuner.setText("Hide");
        btnHideTuner.setToolTipText("Hide the sampling window.");
        btnHideTuner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHideTunerActionPerformed(evt);
            }
        });
        panelTunerControl.add(btnHideTuner);

        splitPaneTuner.setLeftComponent(panelTunerControl);

        add(splitPaneTuner, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveTunerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveTunerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSaveTunerActionPerformed

    private void btnStartTunerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartTunerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnStartTunerActionPerformed

    private void btnStopTunerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopTunerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnStopTunerActionPerformed

    private void btnUpdateConfigurationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateConfigurationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateConfigurationActionPerformed

    private void btnHideTunerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHideTunerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHideTunerActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHideTuner;
    private javax.swing.JButton btnSaveTuner;
    private javax.swing.JButton btnStartTuner;
    private javax.swing.JButton btnStopTuner;
    private javax.swing.JButton btnUpdateConfiguration;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JPanel panelTunerControl;
    private javax.swing.JScrollPane scrollPaneTuner;
    private javax.swing.JSplitPane splitPaneTuner;
    private javax.swing.JTextArea taOverview;
    private javax.swing.JTable tblTuner;
    // End of variables declaration//GEN-END:variables
}
